# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99e1393ff867cc10c99d64d9d76b3d99efd4a28683e1863dd9f8f5c19bff28fa5586a061698a81502cf3ef0501931b6f9c78a3249bd064b3458bdcf92ccd3740

test:
  secret_key_base: 7ae4d3b3c5a2a59b1f11e6b55136befee871b745afca4d91919549fe2b16b6e190dab14c0b9fbf840faf760c0d8fafd9a078eb0878bb1f18a474b3fdd4de8c7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
